<a href="https://colab.research.google.com/github/KrithikaMJ/PANDAS/blob/main/Datascience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PANDAS**
 Import pandas as pd

# New Section

In [9]:
import pandas as pd
data=[20,30,40,90]
s=pd.Series(data)
print(s)

0    20
1    30
2    40
3    90
dtype: int64

In [10]:
import pandas as pd
data=[20,30,40,90]
s=pd.Series(data,index=["A","B","C","D"])
print(s)

A    20
B    30
C    40
D    90
dtype: int64

In [11]:
import pandas as pd
data={"Name":"Krithika","Age":19,"City":"Thrissur"}
s=pd.Series(data)
print(s)

Name    Krithika
Age           19
City    Thrissur
dtype: object

**loc=label and iloc=position**

In [12]:
data=[30,40,20,50,10]
s=pd.Series(data)
print(s)

0    30
1    40
2    20
3    50
4    10
dtype: int64

In [13]:
data=[30,40,20,50,10]
s=pd.Series(data)
print(s.loc[1])

40

In [14]:
data=[30,40,20,50,10]
s=pd.Series(data,index=["A","B","C","D","E"])
print(s.iloc[0])
print(s.loc["B"])
print(s[2:4])

30
40
C    20
D    50
dtype: int64

In [15]:
a=[1,2,3,4,5]
i=pd.Series(a,index=["a","b","c","d","e"])
print(i.iloc[1:3])
print(i.loc["a":"d"])

b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64

In [16]:
import pandas as pd
sales = pd.Series( [1200,850,1500,950,2000],
                   index = ["Monday","Tuesday","Wednesday","Thursday","Friday"]
)
print(sales)

Monday       1200
Tuesday       850
Wednesday    1500
Thursday      950
Friday       2000
dtype: int64

In [17]:
import pandas as pd
sales = pd.Series( [1200,850,1500,950,2000],
                   index = ["Monday","Tuesday","Wednesday","Thursday","Friday"]
)
print(sales)
print("Maximum sale =",sales.max())
print("Minimum sale =",sales.min())
print("Sum of sales =",sales.sum())
print("Below 1000\n",sales[sales<1000])

Monday       1200
Tuesday       850
Wednesday    1500
Thursday      950
Friday       2000
dtype: int64
Maximum sale = 2000
Minimum sale = 850
Sum of sales = 6500
Below 1000
 Tuesday     850
Thursday    950
dtype: int64

In [18]:
import pandas as pd
data=[20,20,30,30,50,60,60,80]
ar=pd.Series(data)
print(ar)
print(ar.unique())
print(ar.nunique())
print(ar.value_counts())                          # count for unique

0    20
1    20
2    30
3    30
4    50
5    60
6    60
7    80
dtype: int64
[20 30 50 60 80]
5
20    2
30    2
60    2
50    1
80    1
Name: count, dtype: int64

In [19]:
a=[None,20,10,None]
ar=pd.Series(a)
print(ar)
print(ar.isnull())
print(ar.notnull())

0     NaN
1    20.0
2    10.0
3     NaN
dtype: float64
0     True
1    False
2    False
3     True
dtype: bool
0    False
1     True
2     True
3    False
dtype: bool

In [20]:
import pandas as pd
marks = pd.Series([78,45,89,None,67,92,56,78,None,34],
                  index=["Anu","Rahul","Meera","Arun","Neha",
                         "vishnu","Diya","Akhil","Riya","Kiran"])

1. find the no of students and total marks
2. find the averge,highest and lowest marks
3. find the name o the students with highest mark
4. check and count the missing values
5. replce the missing value with 0
6. find the unique marks and the no of unique marks
7. find the std who score above 70
8. sort the marks in descending order

In [21]:
import pandas as pd
import numpy as np
data={
   "Name   ":["Alice  ","Bob    ","Charlie","David  ","Emma   "],
   " Age":[20,21,19,22,20],
   "  Marks":[85,72,np.nan,90,65],
   " Attendance":[95,80,75,np.nan,88],
   "City   ":["Kochi  ","Delhi  ","Mumbai ","Kochi  ","Chennai"]
}
df=pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
   Name      Age    Marks   Attendance  City
0  Alice      20     85.0         95.0  Kochi
1  Bob        21     72.0         80.0  Delhi
2  Charlie    19      NaN         75.0  Mumbai
3  David      22     90.0          NaN  Kochi
4  Emma       20     65.0         88.0  Chennai

**Create DataFrame**

In [22]:
print(df.head(3))                                    #for printing needed rows or columns
                                                     #df.head for first and * df.tail for last

   Name      Age    Marks   Attendance  City
0  Alice      20     85.0         95.0  Kochi
1  Bob        21     72.0         80.0  Delhi
2  Charlie    19      NaN         75.0  Mumbai

In [23]:
print(df.tail(2))

   Name      Age    Marks   Attendance  City
3  David      22     90.0          NaN  Kochi
4  Emma       20     65.0         88.0  Chennai

In [24]:
print(df.shape)
print(df.columns)

(5, 5)
Index(['Name   ', ' Age', '  Marks', ' Attendance', 'City   '], dtype='object')

In [25]:
print(df.dtypes)                       #for dtatypes

Name            object
 Age             int64
  Marks        float64
 Attendance    float64
City            object
dtype: object

In [26]:
print(df["  Marks"])                          # Marks change aaki vere eath venelum aakan pattum(name,age,city.......)

0    85.0
1    72.0
2     NaN
3    90.0
4    65.0
Name:   Marks, dtype: float64

In [27]:
print(df.iloc[0:3])

   Name      Age    Marks   Attendance  City
0  Alice      20     85.0         95.0  Kochi
1  Bob        21     72.0         80.0  Delhi
2  Charlie    19      NaN         75.0  Mumbai

In [28]:
print(df.iloc[1:5])                                        # end number include aavilla

   Name      Age    Marks   Attendance  City
1  Bob        21     72.0         80.0  Delhi
2  Charlie    19      NaN         75.0  Mumbai
3  David      22     90.0          NaN  Kochi
4  Emma       20     65.0         88.0  Chennai

In [29]:
print(df.loc[0:3,["Name   ","  Marks"]])                  # end number include aavum

   Name       Marks
0  Alice       85.0
1  Bob         72.0
2  Charlie      NaN
3  David       90.0

In [30]:
print(df[df["  Marks"] > 75])

   Name      Age    Marks   Attendance  City
0  Alice      20     85.0         95.0  Kochi
3  David      22     90.0          NaN  Kochi

In [31]:
print(df[df["  Marks"] < 75])

   Name      Age    Marks   Attendance  City
1  Bob        21     72.0         80.0  Delhi
4  Emma       20     65.0         88.0  Chennai

In [32]:
print(df[df["  Marks"] == 72])

   Name      Age    Marks   Attendance  City
1  Bob        21     72.0         80.0  Delhi

In [33]:
print(df[df["  Marks"] == 75])

Empty DataFrame
Columns: [Name   ,  Age,   Marks,  Attendance, City   ]
Index: []

In [34]:
print(df[df["City   "] == "Kochi  "])

   Name      Age    Marks   Attendance  City
0  Alice      20     85.0         95.0  Kochi
3  David      22     90.0          NaN  Kochi

In [35]:
print(
    df[
    (df["  Marks"] < 75)
           &
    (df[" Attendance"] > 50)
    ]
)

   Name      Age    Marks   Attendance  City
1  Bob        21     72.0         80.0  Delhi
4  Emma       20     65.0         88.0  Chennai

In [36]:
print(df['  Marks'].mean(),": Mean")
print(df['  Marks'].max(),": Max")
print(df['  Marks'].sum(),": Sum")
print(df['  Marks'].min(),": Min")
print(df.sort_values('  Marks'))
print(df.sort_values('  Marks',ascending=False))

78.0 : Mean
90.0 : Max
312.0 : Sum
65.0 : Min
   Name      Age    Marks   Attendance  City
4  Emma       20     65.0         88.0  Chennai
1  Bob        21     72.0         80.0  Delhi
0  Alice      20     85.0         95.0  Kochi
3  David      22     90.0          NaN  Kochi
2  Charlie    19      NaN         75.0  Mumbai
   Name      Age    Marks   Attendance  City
3  David      22     90.0          NaN  Kochi
0  Alice      20     85.0         95.0  Kochi
1  Bob        21     72.0         80.0  Delhi
4  Emma       20     65.0         88.0  Chennai
2  Charlie    19      NaN         75.0  Mumbai

In [37]:
df_renamed = df.rename(
    columns={
        "Marks":"Score",
        "Attendance":"Attendance_percentage"
    }
)
print(df_renamed)
print(df.isna())
print(df.isna().sum())

   Name      Age    Marks   Attendance  City
0  Alice      20     85.0         95.0  Kochi
1  Bob        21     72.0         80.0  Delhi
2  Charlie    19      NaN         75.0  Mumbai
3  David      22     90.0          NaN  Kochi
4  Emma       20     65.0         88.0  Chennai
   Name       Age    Marks   Attendance  City
0    False  False    False        False    False
1    False  False    False        False    False
2    False  False     True        False    False
3    False  False    False         True    False
4    False  False    False        False    False
Name           0
 Age           0
  Marks        1
 Attendance    1
City           0
dtype: int64

In [38]:
print(df.dropna())                                   # dropna remove NaN frm the given

   Name      Age    Marks   Attendance  City
0  Alice      20     85.0         95.0  Kochi
1  Bob        21     72.0         80.0  Delhi
4  Emma       20     65.0         88.0  Chennai

In [39]:
df_forward = df.copy()                            # df_forward.ffill uesd to fill NaN space with above number
df_forward = df_forward.ffill()
print(df_forward)

   Name      Age    Marks   Attendance  City
0  Alice      20     85.0         95.0  Kochi
1  Bob        21     72.0         80.0  Delhi
2  Charlie    19     72.0         75.0  Mumbai
3  David      22     90.0         75.0  Kochi
4  Emma       20     65.0         88.0  Chennai

In [40]:
df_backward = df.copy()                            # df_backward.bfill uesd to fill NaN space with below number
df_backward = df_backward.bfill()
print(df_backward)

   Name      Age    Marks   Attendance  City
0  Alice      20     85.0         95.0  Kochi
1  Bob        21     72.0         80.0  Delhi
2  Charlie    19     90.0         75.0  Mumbai
3  David      22     90.0         88.0  Kochi
4  Emma       20     65.0         88.0  Chennai

In [41]:
df=pd.read_csv("/content/nigeria_messy_sales_dataset (2).csv")
df

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,NaN,NaN,NaN,2025-04-27,Online,NaN
1,Allison Hill,Lagos,Headphones,NaN,267992.94,NaN,2024-03-15,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,NaN,42364.41,NaN,2024-12-10,NaN,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,NaN,279444.94,NaN,2024-04-05,NaN,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,NaN,95899.74,NaN,2025-01-12,NaN,8639bd41-8b15-4d94-a42d-0cd7fd359f6a
...,...,...,...,...,...,...,...,...,...
545,Zachary Mitchell,Ekiti,Monitor,6.0,23989.09,143934.54,2025-07-07,Wholesale,b9744cde-d259-4960-aee3-560792ea1324
546,NaN,Katsina,Tablet,NaN,223764.24,NaN,2025-02-11,Wholesale,NaN
547,Katherine Martinez,Bauchi,Phone,NaN,104084.92,NaN,2025-05-18,Retail,61fa8e7a-078c-46ce-bf02-23bc651ea252
548,Jodi Roach,Niger,Charger,NaN,29756.89,NaN,2025-06-29,Direct,5a9c0679-2c3d-47e2-ad39-da75aee70ab2
549,Brandon Fleming,imo,Camera,NaN,70027.13,NaN,2024-02-20,NaN,46653497-2fe9-42aa-a886-a01136f7a26c

1. Load the Nigeria sales dataset into a DataFrame named sales_df. Display the dataset and identify the number of records and columns available.
2. The manager wants to review basic information about the sales data. Display the first 7 records and the last 5 records.
3. The sales team wants to focus on the Product, Units Sold, Unit Price, and Total Sale information. Display only these details.
4. Find all sales transactions where the Units Sold is greater than 50. Display the complete records.
5. The manager wants to identify transactions where the Unit Price is greater than 100,000. Display the relevant sales records.
6. Find all transactions made through the Online sales channel.
7. The manager wants to know which different states are present in the dataset. Also determine how many different states are available.
8. Find out how many sales transactions belong to each Sales Channel.
9. The company wants to understand the quality of the dataset. Find the number of missing values present in each column.
10. Prepare a new dataset containing only records with complete information. Then find how many records remain after removing incomplete records.

1

In [46]:
df.shape

(550, 9)

2

In [48]:
df.head(7)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,NaN,NaN,NaN,2025-04-27,Online,NaN
1,Allison Hill,Lagos,Headphones,NaN,267992.94,NaN,2024-03-15,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,NaN,42364.41,NaN,2024-12-10,NaN,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,NaN,279444.94,NaN,2024-04-05,NaN,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,NaN,95899.74,NaN,2025-01-12,NaN,8639bd41-8b15-4d94-a42d-0cd7fd359f6a
5,Cristian Santos,Oyo,Camera,NaN,118189.90,NaN,2023-08-30,Direct,225aed6c-f045-4043-a3a6-8a707e710b55
6,Connie Lawrence,Rivers,Tablet,36.0,185141.90,6665108.4,2024-09-10,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e

In [49]:
df.tail(5)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
545,Zachary Mitchell,Ekiti,Monitor,6.0,23989.09,143934.54,2025-07-07,Wholesale,b9744cde-d259-4960-aee3-560792ea1324
546,NaN,Katsina,Tablet,NaN,223764.24,NaN,2025-02-11,Wholesale,NaN
547,Katherine Martinez,Bauchi,Phone,NaN,104084.92,NaN,2025-05-18,Retail,61fa8e7a-078c-46ce-bf02-23bc651ea252
548,Jodi Roach,Niger,Charger,NaN,29756.89,NaN,2025-06-29,Direct,5a9c0679-2c3d-47e2-ad39-da75aee70ab2
549,Brandon Fleming,imo,Camera,NaN,70027.13,NaN,2024-02-20,NaN,46653497-2fe9-42aa-a886-a01136f7a26c

3

In [58]:
(df["Product"],["Units Sold"],["Unit Price"],["Total Sale"])

(0        KEYBOARD
 1      Headphones
 2        Keyboard
 3        Keyboard
 4          Tablet
           ...
 545       Monitor
 546        Tablet
 547         Phone
 548       Charger
 549        Camera
 Name: Product, Length: 550, dtype: object,
 ['Units Sold'],
 ['Unit Price'],
 ['Total Sale'])

4

In [54]:
(df[df["Units Sold"]>50])

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
19,Derek Zuniga,Imo,Headphones,77.0,92649.51,7134012.27,2025-03-18,Online,4459bd6e-c0f6-4229-b25d-42593c4b1eec
31,Zachary Hicks,Anambra,Camera,68.0,15880.87,1079899.16,2024-04-16,Wholesale,fd247c11-bf6b-4cdf-b479-7b6127372b52
32,Anthony Rodriguez,Oyo,MONITOR,96.0,144394.41,13861863.36,2024-09-13,Online,b3b26337-6a74-4bb7-9fa5-e0aa9b11b530
37,Debra Davidson,Benue,Phone,65.0,246587.56,16028191.40,2024-09-11,Wholesale,87365a84-725e-434d-8687-9aa914f573d0
38,Jeffrey Chavez,Rivers,Charger,79.0,73037.87,5769991.73,2023-10-19,Wholesale,ead08c89-13fe-4a29-9c9d-eee0b42a0456
...,...,...,...,...,...,...,...,...,...
515,Julie Dominguez,Cross River,Monitor,59.0,270431.25,15955443.75,2024-02-17,Retail,1be5a4c3-95af-4d0c-8528-5425c7a9f33c
522,Howard Norman,benue,Camera,69.0,84471.72,5828548.68,2024-09-28,NaN,4de1087b-afa1-4a55-8ebe-abaa28597b34
528,Samantha Gardner,Rivers,HEADPHONES,52.0,62543.86,3252280.72,2025-07-07,NaN,2c82989f-fd9c-4bb0-91f1-6485429a4a7c
541,Phillip Berry,Bauchi,Headphones,97.0,115461.94,11199808.18,2024-05-14,NaN,178be968-20f8-4ba2-8f2e-32967184b713
544,Mr. Justin Green III,Sokoto,KEYBOARD,65.0,206948.51,13451653.15,2023-12-02,Online,ec93e596-2b01-4723-8cf6-97a57603c36c

5

In [62]:
(df[df["Unit Price"]>100000])

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
1,Allison Hill,Lagos,Headphones,NaN,267992.94,NaN,2024-03-15,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
3,Angie Henderson,Delta,Keyboard,NaN,279444.94,NaN,2024-04-05,NaN,74503887-48d9-4846-95c5-51fcfba57cc8
5,Cristian Santos,Oyo,Camera,NaN,118189.90,NaN,2023-08-30,Direct,225aed6c-f045-4043-a3a6-8a707e710b55
6,Connie Lawrence,Rivers,Tablet,36.0,185141.90,6665108.40,2024-09-10,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e
7,Abigail Shaffer,Imo,Keyboard,NaN,252859.28,NaN,2024-09-04,Online,54a7b69b-1cd6-4b09-8f0e-6d2b315c167a
...,...,...,...,...,...,...,...,...,...
542,Jennifer Banks,Imo,Monitor,NaN,222053.68,NaN,2025-03-14,Online,cf133b65-d450-4fa2-98e7-0aebe7b33085
543,Brian Fitzgerald,Katsina,Laptop,NaN,237254.18,NaN,2024-07-29,NaN,f1394e3c-0aee-4557-9f5d-f91254e07431
544,Mr. Justin Green III,Sokoto,KEYBOARD,65.0,206948.51,13451653.15,2023-12-02,Online,ec93e596-2b01-4723-8cf6-97a57603c36c
546,NaN,Katsina,Tablet,NaN,223764.24,NaN,2025-02-11,Wholesale,NaN
547,Katherine Martinez,Bauchi,Phone,NaN,104084.92,NaN,2025-05-18,Retail,61fa8e7a-078c-46ce-bf02-23bc651ea252

6

In [63]:
df[df["Sales Channel"]=="Online"]

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,NaN,NaN,NaN,2025-04-27,Online,NaN
7,Abigail Shaffer,Imo,Keyboard,NaN,252859.28,NaN,2024-09-04,Online,54a7b69b-1cd6-4b09-8f0e-6d2b315c167a
19,Derek Zuniga,Imo,Headphones,77.0,92649.51,7134012.27,2025-03-18,Online,4459bd6e-c0f6-4229-b25d-42593c4b1eec
23,Patty Perez,Delta,Camera,NaN,188963.51,NaN,2023-10-13,Online,77242041-1e43-4bd2-aaf4-07f70fe76149
24,Ethan Adams,Ekiti,LAPTOP,4.0,179274.43,717097.72,2023-12-14,Online,afa28559-67c9-4204-a8e3-33b64e8adc4b
...,...,...,...,...,...,...,...,...,...
525,Jasmine Beltran,Delta,Tablet,NaN,54216.67,NaN,2025-02-03,Online,b60e695c-1759-4a96-a5f8-8c7453ea4919
534,William Gould,Abuja,Laptop,NaN,90133.43,NaN,2025-05-26,Online,c7ecfe71-d493-47fc-8fc9-8d2e030f9be9
538,Austin Osborne,Ekiti,Keyboard,NaN,203271.97,NaN,2025-06-24,Online,eadc9960-4242-41e2-960b-e0f495132c22
542,Jennifer Banks,Imo,Monitor,NaN,222053.68,NaN,2025-03-14,Online,cf133b65-d450-4fa2-98e7-0aebe7b33085
544,Mr. Justin Green III,Sokoto,KEYBOARD,65.0,206948.51,13451653.15,2023-12-02,Online,ec93e596-2b01-4723-8cf6-97a57603c36c

7

In [73]:
print(df["State"].unique())
(df["State"].nunique())

['rivers' 'Lagos' 'Anambra' 'Delta' 'Oyo' 'Rivers' 'Imo' 'Kano' 'plateau'
 'Niger' 'Abuja' 'Enugu' 'Bauchi' 'Katsina' 'lagos' 'Ekiti' 'Plateau'
 'Kaduna' 'Sokoto' 'kano' 'Benue' 'Osun' 'imo' 'Borno' 'enugu' 'anambra'
 'katsina' 'delta' 'Cross River' 'oyo' 'osun' 'kaduna' 'niger' 'borno'
 'abuja' 'bauchi' 'cross river' 'ekiti' 'sokoto' 'benue']

40

8

In [74]:
df["Sales Channel"].value_counts()

Sales Channel
Direct       124
Wholesale    111
Retail       108
Online       101
Name: count, dtype: int64

9

In [75]:
df.isna()

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,True,False,False,True,True,True,False,False,True
1,False,False,False,True,False,True,False,False,False
2,False,False,False,True,False,True,False,True,False
3,False,False,False,True,False,True,False,True,False
4,False,False,False,True,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...
545,False,False,False,False,False,False,False,False,False
546,True,False,False,True,False,True,False,False,True
547,False,False,False,True,False,True,False,False,False
548,False,False,False,True,False,True,False,False,False
549,False,False,False,True,False,True,False,True,False

10

In [76]:
df.dropna()

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
6,Connie Lawrence,Rivers,Tablet,36.0,185141.90,6665108.40,2024-09-10,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e
11,Monica Herrera,Abuja,Laptop,3.0,153159.37,459478.11,2025-05-02,Retail,317304b5-c1dd-484a-aca5-8d95915a1c30
12,Jamie Arnold,Lagos,Tablet,43.0,147209.07,6329990.01,2023-11-10,Wholesale,a383889a-db2c-4ac8-9c67-83932ced3c0d
18,Holly Wood,lagos,Headphones,43.0,125253.81,5385913.83,2023-11-23,Direct,6231ee73-42c2-42eb-81bf-9e733f800385
19,Derek Zuniga,Imo,Headphones,77.0,92649.51,7134012.27,2025-03-18,Online,4459bd6e-c0f6-4229-b25d-42593c4b1eec
...,...,...,...,...,...,...,...,...,...
517,Judith Carter,Kano,Laptop,46.0,170251.85,7831585.10,2023-08-25,Wholesale,1ee89a4c-6811-44e2-9064-7c59774f6354
527,Monica Miller,Lagos,Laptop,47.0,5189.60,243911.20,2025-05-01,Retail,4c80d33a-ad5b-43c8-8c88-0714837217e0
537,Lawrence Harrington,Rivers,Monitor,16.0,254908.01,4078528.16,2025-07-05,Direct,15839b99-a50a-43dc-b004-e897a15b2e18
544,Mr. Justin Green III,Sokoto,KEYBOARD,65.0,206948.51,13451653.15,2023-12-02,Online,ec93e596-2b01-4723-8cf6-97a57603c36c
545,Zachary Mitchell,Ekiti,Monitor,6.0,23989.09,143934.54,2025-07-07,Wholesale,b9744cde-d259-4960-aee3-560792ea1324